name: CI

on:
  push:
    branches-ignore:
      - "wip/**"
      - "tmp/**"
    tags: ["v*"]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - ".git*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "*.txt"
      - ".git*"

env:
  CONFIGURATION: Release
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Display .NET info
        run: dotnet --info

      - name: Pack
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true

          $commitTimestamp = git log -1 --format=%cI
          $versionSuffix = ([datetimeoffset]$commitTimestamp).ToUniversalTime().ToString('yyyyMMdd''t''HHmm')

          $releaseNotesFile = [System.IO.Path]::GetTempFileName()
          $tag = '${{ github.ref_name }}'
          $isTag = '${{ github.ref_type }}' -eq 'tag'

          # if the tag starts with "v", as in "v1.0.0", assume it's a release
          if ($isTag -and $tag -clike 'v*') {
            $url = '${{ github.server_url }}/${{ github.repository }}'
            Add-Content $releaseNotesFile -Encoding UTF8 "See: ${url}/releases/tag/$tag"
            Add-Content $releaseNotesFile -Encoding UTF8 ''
            # if tag ends in "-" followed by dot-separated identifiers...
            if ($tag -match '(?<=-)[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*$') {
              $versionSuffix = $matches[0] # ...then use as suffix for pre-release
            } else {
              $versionSuffix = $null       # ... else use no suffix for a release
            }
          }

          Add-Content $releaseNotesFile -Encoding UTF8 "Commit @ ${{ github.sha }}"
          $packArgs = @(
            '-p:PackageReleaseNotesFile=$releaseNotesFile',
            '-o', 'dist'
          )
          if ($versionSuffix) {
            $packArgs += @('--version-suffix', $versionSuffix)
          }
          dotnet pack @packArgs CSharpSyntaxValidator.cs

      - name: Verify SourceLink
        run: |
          dotnet tool install sourcelink --version 3.1.1
          nupkg=$(find dist -type f -name '*.nupkg' | head -1)
          if [ -z "$nupkg" ]; then
            echo >&2 "No package file found"
            exit 1
          fi
          tmpdir=$(mktemp -d)
          unzip -d "$tmpdir" "$nupkg"
          find "$tmpdir" -type f -name CSharpSyntaxValidator.dll |
            xargs -t -n 1 dotnet sourcelink test

      - name: Validate Package
        run: |
          dotnet tool install meziantou.framework.nugetpackagevalidation.tool --version 1.0.41
          find dist -type f -name '*.nupkg' |
            xargs -t -n 1 dotnet meziantou.validate-nuget-package --excluded-rules IconMustBeSet,XmlDocumentationMustBePresent,ReadmeMustBeSet

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: dist/*.nupkg
